Test Failure in pyvcloud due to href issue.
Traceback (most recent call last):
File "/data/jenkins/jenkins-CToT4-pysdk-sp-main-daily-317/jenkins-venv/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1350, in get_linked_resource
return self.get_resource(find_link(resource, rel, media_type).href)
File "/data/jenkins/jenkins-CToT4-pysdk-sp-main-daily-317/jenkins-venv/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1613, in find_link
raise MissingLinkException(resource.get('href'), rel, media_type)
pyvcloud.vcd.exceptions.MissingLinkException: ('https://wdc-vcd-sp-static-34-57.eng.vmware.com/api/admin/vdc/8e49800a-e8e3-4e04-92e7-d1c777aed72e', <RelationType.DOWN: 'down'>, 'application/vnd.vmware.vcloud.controlAccess+xml'); href: https://wdc-vcd-sp-static-34-57.eng.vmware.com/api/admin/vdc/8e49800a-e8e3-4e04-92e7-d1c777aed72e, rel: RelationType.DOWN, mediaType: application/vnd.vmware.vcloud.controlAccess+xml

Status code: 403/ACCESS_TO_RESOURCE_IS_FORBIDDEN, [ 8ddfd5b5-7342-4173-820f-4af3351d48ac ] Either you need some or all of the following rights [ORG_VDC_ADMIN_VIEW] to perform operations [ORGANIZATION_VDC_VIEW] for 8e49800a-e8e3-4e04-92e7-d1c777aed72e or the target entity is invalid. (request id: 8ddfd5b5-7342-4173-820f-4af3351d48ac)