VCDA-331: catalog_item download fails with 'No such file or directory' error. (#175)
This issue happens because the check `if num_bytes != source_file['size']:` fails because source_file['size'] value is str instead of int.

Before fix:
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd catalog download Tester v1 test-ova1.ova
catalogItemEnableDownload: Enabling Catalog Item v1(a96ab70b-4641-4290-935b-27935e52b2b7)
download 68,096 of 68,096 bytes, 100%
Usage: vcd catalog download [OPTIONS] <catalog-name> <item-name> [file-name]

Error: [WinError 2] The system cannot find the file specified: 'test-ova1.ova'

After fix:
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd catalog download Tester v1 test-ova1.ova
catalogItemEnableDownload: Enabling Catalog Item v1(a96ab70b-4641-4290-935b-27935e52b2b7)
catalogItemEnableDownload: Enabling Catalog Item v1(a96ab70b-4641-4290-935b-27935e52b2b7)
download 68,096 of 68,096 bytes, 100%
property    value
----------  -------------
file        test-ova1.ova
size        81920